title: Hello, world! I'm David Makin
description: > # this means to ignore newlines until "baseurl:"
  David Makin.
  He lives in Manchester, likes coffee and writes code.
  Occasionally he throws axes and goes snowboarding
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.sleep-er.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: pwnedsleeper #if your site has a twitter account, enter it here

# Author Settings
author: David Makin # add your name
author-img: david-makin.webp # add your photo
author-img-header: large-me.webp # add your photo
about-author: I am a developer. Usually focusing on backend services in PHP and Typescript. # add description
social-twitter: pwnedsleeper # add your Twitter handle
social-facebook: david.makin # add your Facebook handle
social-github: DavidMakin # add your Github handle
social-linkedin: david-makin-0a14213 # add your Linkedin handle
social-email: david[ at ]sleep-er.co.uk # add your Email address

# Disqus
discus-identifier: davidmakin # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
